### PR TITLE
Use Optimist

### PR DESCRIPTION
**Pull request by NickLaMuro**
`Trollop` is a deprecated gem, and has been renamed/replaced by `Optimist`.

Links
-----
* Org search of current usage of old gem (hides some irrelevant repos):  [search](https://github.com/search?l=&q=Trollop+repo%3AManageIQ%2Fmanageiq+repo%3AManageIQ%2Fmanageiq-release+repo%3AManageIQ%2Fmanageiq-appliance_console+repo%3AManageIQ%2Fmanageiq-appliance-build+repo%3AManageIQ%2Fmanageiq-api+repo%3AManageIQ%2Fmanageiq-providers-vmware+repo%3AManageIQ%2Fhttpd_configmap_generator+repo%3AManageIQ%2Fguides&type=Code)
* https://github.com/ManageIQ/manageiq/pull/18246

### CODE REVIEW

**Comment by jvlcek** [comment]
@NickLaMuro How did you test/confirm this? Could you add a new spec test to go with these changes?

Thank you. JoeV

**Comment by NickLaMuro** [comment]
@jvlcek Since the changes are in the `bin` file, I don't think that is really easy to do.  I would say the easiest way to do it is to just run `bin/httpd_configmap_generator --help` and confirm that it doesn't blowup.

**Comment by NickLaMuro** [comment]
@jvlcek Added a spec, but let me know if you would rather see that spec in a separate PR, and then this PR can build off of it.

**Comment by jvlcek** [comment]
@NickLaMuro OK. @kbrock just told me that `Trollop` has been renamed to `Optimist` so all should be the same anyway. 👍

**Comment by NickLaMuro** [comment]
That " @kbrock guy" also did the rename too... go figure 😉

**Comment by abellotti** [comment]
he was very "optimist"ic with that rename 😏 sorry, couldn't help it.

**Pull request merged**
